"""
Health Status Reporting and Alerting System for Email Agent

This module implements comprehensive health monitoring, reporting, and alerting
for all system components with trend analysis, threshold violations, and
escalation procedures for federal-grade email processing systems.

Requirements: 7.3, 7.5, 7.6
"""

import time
import threading
import smtplib
import json
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Callable, Set
from dataclasses import dataclass, field
from enum import Enum
import logging
from collections import defaultdict, deque
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
import statistics

from .metrics_collector import MetricsCollector, SecurityIncidentType
from .performance_monitor import PerformanceMonitor, BottleneckDetection, SeverityLevel

logger = logging.getLogger(__name__)


class HealthStatus(Enum):
    """Overall health status levels"""
    HEALTHY = "healthy"
    WARNING = "warning"
    DEGRADED = "degraded"
    CRITICAL = "critical"
    UNKNOWN = "unknown"


class ComponentType(Enum):
    """Types of system components monitored"""
    EMAIL_CLIENT = "email_client"
    DATABASE = "database"
    REDIS_QUEUE = "redis_queue"
    CLASSIFICATION_ENGINE = "classification_engine"
    SECURITY_VALIDATOR = "security_validator"
    CONTENT_EXTRACTOR = "content_extractor"
    EVENT_PUBLISHER = "event_publisher"
    DELIVERY_MANAGER = "delivery_manager"
    CONNECTION_POOL = "connection_pool"
    IDLE_CONTROLLER = "idle_controller"
    POLLING_ENGINE = "polling_engine"


class AlertType(Enum):
    """Types of alerts that can be triggered"""
    THRESHOLD_VIOLATION = "threshold_violation"
    COMPONENT_FAILURE = "component_failure"
    SECURITY_INCIDENT = "security_incident"
    PERFORMANCE_DEGRADATION = "performance_degradation"
    RESOURCE_EXHAUSTION = "resource_exhaustion"
    CONNECTIVITY_ISSUE = "connectivity_issue"
    DATA_INTEGRITY_ISSUE = "data_integrity_issue"


class AlertSeverity(Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class ComponentHealth:
    """Health status of individual system component"""
    component_type: ComponentType
    component_id: str
    status: HealthStatus
    last_check: datetime
    response_time_ms: Optional[float]
    error_count: int
    uptime_percentage: float
    last_error: Optional[str]
    last_successful_operation: Optional[datetime]
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HealthThreshold:
    """Threshold configuration for health monitoring"""
    metric_name: str
    warning_threshold: float
    critical_threshold: float
    comparison_operator: str  # "gt", "lt", "eq"
    check_interval_seconds: int
    consecutive_violations_required: int = 1


@dataclass
class HealthAlert:
    """Health alert generated by the system"""
    alert_id: str
    timestamp: datetime
    alert_type: AlertType
    severity: AlertSeverity
    component: str
    title: str
    description: str
    current_value: Optional[float]
    threshold_value: Optional[float]
    impact_assessment: str
    recommended_actions: List[str]
    escalation_level: int = 0
    acknowledged: bool = False
    resolved: bool = False
    resolution_time: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HealthTrend:
    """Health trend analysis for components"""
    component: str
    metric_name: str
    trend_direction: str  # "improving", "stable", "degrading"
    trend_strength: float  # 0.0 to 1.0
    data_points: int
    time_window_hours: int
    prediction: Optional[str] = None


@dataclass
class SystemHealthReport:
    """Comprehensive system health report"""
    report_id: str
    timestamp: datetime
    overall_health: HealthStatus
    component_health: Dict[str, ComponentHealth]
    active_alerts: List[HealthAlert]
    health_trends: List[HealthTrend]
    performance_summary: Dict[str, Any]
    security_summary: Dict[str, Any]
    recommendations: List[str]
    next_report_time: datetime


@dataclass
class EscalationRule:
    """Escalation rule for persistent health issues"""
    alert_type: AlertType
    severity: AlertSeverity
    escalation_delay_minutes: int
    max_escalation_level: int
    notification_channels: List[str]
    escalation_actions: List[str]


class HealthReporter:
    """
    Comprehensive health status reporting and alerting system
    
    Monitors all system components, generates health reports with trend analysis,
    triggers alerts for threshold violations, and implements escalation procedures
    for persistent health issues.
    """
    
    def __init__(self, metrics_collector: MetricsCollector, 
                 performance_monitor: PerformanceMonitor,
                 check_interval: int = 60):
        """
        Initialize health reporter
        
        Args:
            metrics_collector: Metrics collection system
            performance_monitor: Performance monitoring system
            check_interval: Health check interval in seconds
        """
        self.metrics_collector = metrics_collector
        self.performance_monitor = performance_monitor
        self.check_interval = check_interval
        
        self._lock = threading.RLock()
        self._monitoring_active = False
        self._monitor_thread: Optional[threading.Thread] = None
        self._escalation_thread: Optional[threading.Thread] = None
        
        # Health data storage
        self._component_health: Dict[str, ComponentHealth] = {}
        self._health_history: Dict[str, deque] = defaultdict(lambda: deque(maxlen=1000))
        self._active_alerts: Dict[str, HealthAlert] = {}
        self._alert_history: deque = deque(maxlen=5000)
        self._health_trends: Dict[str, HealthTrend] = {}
        
        # Configuration
        self._health_thresholds: Dict[str, HealthThreshold] = {}
        self._escalation_rules: Dict[str, EscalationRule] = {}
        self._notification_channels: Dict[str, Callable] = {}
        
        # Tracking
        self._threshold_violations: Dict[str, int] = defaultdict(int)
        self._last_escalation: Dict[str, datetime] = {}
        
        # Initialize default thresholds
        self._initialize_default_thresholds()
        
        # Initialize default escalation rules
        self._initialize_default_escalation_rules()
        
        logger.info("HealthReporter initialized with %ds check interval", check_interval)
    
    def _initialize_default_thresholds(self) -> None:
        """Initialize default health thresholds"""
        default_thresholds = [
            HealthThreshold("cpu_usage", 80.0, 95.0, "gt", 60, 2),
            HealthThreshold("memory_usage", 85.0, 95.0, "gt", 60, 2),
            HealthThreshold("disk_usage", 90.0, 98.0, "gt", 300, 1),
            HealthThreshold("connection_errors", 5, 10, "gt", 300, 1),
            HealthThreshold("processing_latency", 5000.0, 10000.0, "gt", 120, 3),
            HealthThreshold("classification_accuracy", 90.0, 85.0, "lt", 600, 2),
            HealthThreshold("queue_depth", 100, 500, "gt", 60, 2),
            HealthThreshold("security_incidents", 1, 5, "gt", 300, 1),
            HealthThreshold("uptime_percentage", 99.0, 95.0, "lt", 3600, 1)
        ]
        
        for threshold in default_thresholds:
            self._health_thresholds[threshold.metric_name] = threshold
    
    def _initialize_default_escalation_rules(self) -> None:
        """Initialize default escalation rules"""
        default_rules = [
            EscalationRule(
                AlertType.COMPONENT_FAILURE, AlertSeverity.CRITICAL,
                5, 3, ["email", "sms"], ["restart_component", "failover"]
            ),
            EscalationRule(
                AlertType.SECURITY_INCIDENT, AlertSeverity.CRITICAL,
                1, 2, ["email", "sms", "security_team"], ["isolate_component", "security_audit"]
            ),
            EscalationRule(
                AlertType.THRESHOLD_VIOLATION, AlertSeverity.CRITICAL,
                10, 2, ["email"], ["scale_resources", "optimize_performance"]
            ),
            EscalationRule(
                AlertType.PERFORMANCE_DEGRADATION, AlertSeverity.ERROR,
                15, 2, ["email"], ["performance_analysis", "resource_optimization"]
            )
        ]
        
        for rule in default_rules:
            key = f"{rule.alert_type.value}_{rule.severity.value}"
            self._escalation_rules[key] = rule
    
    def register_component(self, component_type: ComponentType, component_id: str,
                          health_check_func: Optional[Callable] = None) -> None:
        """Register a component for health monitoring"""
        with self._lock:
            key = f"{component_type.value}:{component_id}"
            
            self._component_health[key] = ComponentHealth(
                component_type=component_type,
                component_id=component_id,
                status=HealthStatus.UNKNOWN,
                last_check=datetime.now(),
                response_time_ms=None,
                error_count=0,
                uptime_percentage=100.0,
                last_error=None,
                last_successful_operation=None
            )
            
            if health_check_func:
                self._component_health[key].metadata["health_check_func"] = health_check_func
            
            logger.info("Registered component for health monitoring: %s", key)
    
    def register_notification_channel(self, channel_name: str, 
                                    notification_func: Callable[[HealthAlert], None]) -> None:
        """Register notification channel for alerts"""
        self._notification_channels[channel_name] = notification_func
        logger.info("Registered notification channel: %s", channel_name)
    
    def set_health_threshold(self, metric_name: str, warning_threshold: float,
                           critical_threshold: float, comparison_operator: str = "gt",
                           check_interval: int = 60, consecutive_violations: int = 1) -> None:
        """Set custom health threshold"""
        threshold = HealthThreshold(
            metric_name=metric_name,
            warning_threshold=warning_threshold,
            critical_threshold=critical_threshold,
            comparison_operator=comparison_operator,
            check_interval_seconds=check_interval,
            consecutive_violations_required=consecutive_violations
        )
        
        with self._lock:
            self._health_thresholds[metric_name] = threshold
        
        logger.info("Set health threshold for %s: warning=%.2f, critical=%.2f",
                   metric_name, warning_threshold, critical_threshold)
    
    def start_monitoring(self) -> None:
        """Start health monitoring"""
        if self._monitoring_active:
            logger.warning("Health monitoring already active")
            return
        
        self._monitoring_active = True
        
        # Start main monitoring thread
        self._monitor_thread = threading.Thread(target=self._monitoring_loop, daemon=True)
        self._monitor_thread.start()
        
        # Start escalation thread
        self._escalation_thread = threading.Thread(target=self._escalation_loop, daemon=True)
        self._escalation_thread.start()
        
        logger.info("Health monitoring started")
    
    def stop_monitoring(self) -> None:
        """Stop health monitoring"""
        self._monitoring_active = False
        
        if self._monitor_thread:
            self._monitor_thread.join(timeout=5)
        
        if self._escalation_thread:
            self._escalation_thread.join(timeout=5)
        
        logger.info("Health monitoring stopped")
    
    def update_component_health(self, component_type: ComponentType, component_id: str,
                              status: HealthStatus, response_time_ms: Optional[float] = None,
                              error_message: Optional[str] = None) -> None:
        """Update health status of a component"""
        with self._lock:
            key = f"{component_type.value}:{component_id}"
            
            if key not in self._component_health:
                self.register_component(component_type, component_id)
            
            component = self._component_health[key]
            previous_status = component.status
            
            # Update component health
            component.status = status
            component.last_check = datetime.now()
            component.response_time_ms = response_time_ms
            
            if error_message:
                component.error_count += 1
                component.last_error = error_message
            elif status == HealthStatus.HEALTHY:
                component.last_successful_operation = datetime.now()
            
            # Calculate uptime percentage (simplified)
            if status == HealthStatus.HEALTHY:
                component.uptime_percentage = min(100.0, component.uptime_percentage + 0.1)
            else:
                component.uptime_percentage = max(0.0, component.uptime_percentage - 1.0)
            
            # Store in history
            self._health_history[key].append({
                'timestamp': datetime.now(),
                'status': status,
                'response_time_ms': response_time_ms,
                'error_message': error_message
            })
            
            # Check for status changes that require alerts
            if previous_status != status and status in [HealthStatus.CRITICAL, HealthStatus.DEGRADED]:
                self._trigger_component_alert(component, previous_status)
    
    def _monitoring_loop(self) -> None:
        """Main health monitoring loop"""
        while self._monitoring_active:
            try:
                # Check component health
                self._check_all_components()
                
                # Check threshold violations
                self._check_threshold_violations()
                
                # Analyze health trends
                self._analyze_health_trends()
                
                # Generate periodic health reports
                self._generate_periodic_reports()
                
                time.sleep(self.check_interval)
                
            except Exception as e:
                logger.error("Error in health monitoring loop: %s", e)
                time.sleep(self.check_interval)
    
    def _escalation_loop(self) -> None:
        """Escalation monitoring loop"""
        while self._monitoring_active:
            try:
                self._process_escalations()
                time.sleep(60)  # Check escalations every minute
                
            except Exception as e:
                logger.error("Error in escalation loop: %s", e)
                time.sleep(60)
    
    def _check_all_components(self) -> None:
        """Check health of all registered components"""
        for key, component in self._component_health.items():
            try:
                # Run custom health check if available
                health_check_func = component.metadata.get("health_check_func")
                if health_check_func:
                    start_time = time.time()
                    try:
                        is_healthy = health_check_func()
                        response_time = (time.time() - start_time) * 1000
                        
                        status = HealthStatus.HEALTHY if is_healthy else HealthStatus.DEGRADED
                        self.update_component_health(
                            component.component_type, component.component_id,
                            status, response_time
                        )
                    except Exception as e:
                        response_time = (time.time() - start_time) * 1000
                        self.update_component_health(
                            component.component_type, component.component_id,
                            HealthStatus.CRITICAL, response_time, str(e)
                        )
                
            except Exception as e:
                logger.error("Error checking component health %s: %s", key, e)
    
    def _check_threshold_violations(self) -> None:
        """Check for threshold violations in metrics"""
        current_time = datetime.now()
        
        for metric_name, threshold in self._health_thresholds.items():
            try:
                # Get current metric value
                current_value = self._get_current_metric_value(metric_name)
                if current_value is None:
                    continue
                
                # Check threshold violation
                violation_detected = self._check_threshold_violation(current_value, threshold)
                
                if violation_detected:
                    self._threshold_violations[metric_name] += 1
                    
                    # Check if consecutive violations threshold is met
                    if self._threshold_violations[metric_name] >= threshold.consecutive_violations_required:
                        severity = self._determine_violation_severity(current_value, threshold)
                        self._trigger_threshold_alert(metric_name, current_value, threshold, severity)
                        self._threshold_violations[metric_name] = 0  # Reset counter
                else:
                    self._threshold_violations[metric_name] = 0  # Reset counter
                
            except Exception as e:
                logger.error("Error checking threshold for %s: %s", metric_name, e)
    
    def _get_current_metric_value(self, metric_name: str) -> Optional[float]:
        """Get current value for a metric"""
        try:
            if metric_name == "cpu_usage":
                metrics = self.performance_monitor.get_current_performance_status()
                return metrics.get("resource_utilization", {}).get("cpu")
            
            elif metric_name == "memory_usage":
                metrics = self.performance_monitor.get_current_performance_status()
                return metrics.get("resource_utilization", {}).get("memory")
            
            elif metric_name == "processing_latency":
                latency_metrics = self.metrics_collector.get_processing_latency_metrics(1)
                return latency_metrics.get("average_latency_ms")
            
            elif metric_name == "classification_accuracy":
                accuracy_metrics = self.metrics_collector.get_classification_accuracy_metrics()
                return accuracy_metrics.get("overall_accuracy")
            
            elif metric_name == "queue_depth":
                metrics = self.performance_monitor.get_current_performance_status()
                queue_status = metrics.get("queue_status", {})
                if queue_status:
                    return max([q.get("depth", 0) for q in queue_status.values()])
            
            elif metric_name == "security_incidents":
                security_metrics = self.metrics_collector.get_security_incident_metrics(1)
                return security_metrics.get("unresolved_incidents")
            
            elif metric_name == "uptime_percentage":
                uptime_metrics = self.metrics_collector.get_system_uptime_metrics()
                return min(100.0, uptime_metrics.get("uptime_hours", 0) / 24 * 100)
            
            return None
            
        except Exception as e:
            logger.error("Error getting metric value for %s: %s", metric_name, e)
            return None
    
    def _check_threshold_violation(self, value: float, threshold: HealthThreshold) -> bool:
        """Check if a value violates the threshold"""
        if threshold.comparison_operator == "gt":
            return value > threshold.warning_threshold
        elif threshold.comparison_operator == "lt":
            return value < threshold.warning_threshold
        elif threshold.comparison_operator == "eq":
            return abs(value - threshold.warning_threshold) < 0.001
        return False
    
    def _determine_violation_severity(self, value: float, threshold: HealthThreshold) -> AlertSeverity:
        """Determine severity of threshold violation"""
        if threshold.comparison_operator == "gt":
            if value >= threshold.critical_threshold:
                return AlertSeverity.CRITICAL
            else:
                return AlertSeverity.WARNING
        elif threshold.comparison_operator == "lt":
            if value <= threshold.critical_threshold:
                return AlertSeverity.CRITICAL
            else:
                return AlertSeverity.WARNING
        else:
            return AlertSeverity.WARNING
    
    def _trigger_threshold_alert(self, metric_name: str, current_value: float,
                               threshold: HealthThreshold, severity: AlertSeverity) -> None:
        """Trigger alert for threshold violation"""
        alert_id = f"THR_{metric_name}_{int(time.time())}"
        
        alert = HealthAlert(
            alert_id=alert_id,
            timestamp=datetime.now(),
            alert_type=AlertType.THRESHOLD_VIOLATION,
            severity=severity,
            component=f"system:{metric_name}",
            title=f"Threshold Violation: {metric_name}",
            description=f"{metric_name} is {current_value:.2f}, exceeding threshold of {threshold.warning_threshold:.2f}",
            current_value=current_value,
            threshold_value=threshold.warning_threshold,
            impact_assessment=self._assess_threshold_impact(metric_name, current_value, severity),
            recommended_actions=self._get_threshold_recommendations(metric_name, severity)
        )
        
        self._add_alert(alert)
        logger.warning("Threshold violation alert: %s", alert.description)
    
    def _trigger_component_alert(self, component: ComponentHealth, previous_status: HealthStatus) -> None:
        """Trigger alert for component status change"""
        alert_id = f"CMP_{component.component_type.value}_{component.component_id}_{int(time.time())}"
        
        severity = AlertSeverity.CRITICAL if component.status == HealthStatus.CRITICAL else AlertSeverity.ERROR
        
        alert = HealthAlert(
            alert_id=alert_id,
            timestamp=datetime.now(),
            alert_type=AlertType.COMPONENT_FAILURE,
            severity=severity,
            component=f"{component.component_type.value}:{component.component_id}",
            title=f"Component Status Change: {component.component_id}",
            description=f"Component {component.component_id} status changed from {previous_status.value} to {component.status.value}",
            current_value=None,
            threshold_value=None,
            impact_assessment=self._assess_component_impact(component),
            recommended_actions=self._get_component_recommendations(component)
        )
        
        if component.last_error:
            alert.metadata["last_error"] = component.last_error
        
        self._add_alert(alert)
        logger.error("Component failure alert: %s", alert.description)
    
    def _add_alert(self, alert: HealthAlert) -> None:
        """Add alert to active alerts and trigger notifications"""
        with self._lock:
            self._active_alerts[alert.alert_id] = alert
            self._alert_history.append(alert)
        
        # Trigger immediate notifications
        self._send_alert_notifications(alert)
    
    def _send_alert_notifications(self, alert: HealthAlert) -> None:
        """Send alert notifications through configured channels"""
        for channel_name, notification_func in self._notification_channels.items():
            try:
                notification_func(alert)
            except Exception as e:
                logger.error("Error sending notification via %s: %s", channel_name, e)
    
    def _process_escalations(self) -> None:
        """Process alert escalations for persistent issues"""
        current_time = datetime.now()
        
        for alert_id, alert in list(self._active_alerts.items()):
            if alert.resolved or alert.acknowledged:
                continue
            
            # Find applicable escalation rule
            rule_key = f"{alert.alert_type.value}_{alert.severity.value}"
            escalation_rule = self._escalation_rules.get(rule_key)
            
            if not escalation_rule:
                continue
            
            # Check if escalation is due
            time_since_alert = (current_time - alert.timestamp).total_seconds() / 60
            
            if time_since_alert >= escalation_rule.escalation_delay_minutes:
                last_escalation = self._last_escalation.get(alert_id)
                
                if (not last_escalation or 
                    (current_time - last_escalation).total_seconds() / 60 >= escalation_rule.escalation_delay_minutes):
                    
                    if alert.escalation_level < escalation_rule.max_escalation_level:
                        self._escalate_alert(alert, escalation_rule)
    
    def _escalate_alert(self, alert: HealthAlert, rule: EscalationRule) -> None:
        """Escalate an alert to the next level"""
        alert.escalation_level += 1
        self._last_escalation[alert.alert_id] = datetime.now()
        
        logger.warning("Escalating alert %s to level %d", alert.alert_id, alert.escalation_level)
        
        # Execute escalation actions
        for action in rule.escalation_actions:
            try:
                self._execute_escalation_action(alert, action)
            except Exception as e:
                logger.error("Error executing escalation action %s: %s", action, e)
        
        # Send escalated notifications
        escalated_alert = HealthAlert(
            alert_id=f"{alert.alert_id}_ESC_{alert.escalation_level}",
            timestamp=datetime.now(),
            alert_type=alert.alert_type,
            severity=AlertSeverity.CRITICAL,  # Escalated alerts are always critical
            component=alert.component,
            title=f"ESCALATED: {alert.title}",
            description=f"Alert escalated to level {alert.escalation_level}: {alert.description}",
            current_value=alert.current_value,
            threshold_value=alert.threshold_value,
            impact_assessment=f"ESCALATED: {alert.impact_assessment}",
            recommended_actions=alert.recommended_actions + [f"Escalation level {alert.escalation_level} reached"],
            escalation_level=alert.escalation_level
        )
        
        self._send_alert_notifications(escalated_alert)
    
    def _execute_escalation_action(self, alert: HealthAlert, action: str) -> None:
        """Execute an escalation action"""
        if action == "restart_component":
            logger.warning("Escalation action: restart_component for %s", alert.component)
            # Implementation would depend on component management system
        
        elif action == "failover":
            logger.warning("Escalation action: failover for %s", alert.component)
            # Implementation would depend on failover system
        
        elif action == "isolate_component":
            logger.critical("Escalation action: isolate_component for %s", alert.component)
            # Implementation would depend on security isolation system
        
        elif action == "security_audit":
            logger.critical("Escalation action: security_audit triggered")
            # Implementation would depend on security audit system
        
        elif action == "scale_resources":
            logger.warning("Escalation action: scale_resources for %s", alert.component)
            # Implementation would depend on auto-scaling system
        
        else:
            logger.info("Unknown escalation action: %s", action)
    
    def _analyze_health_trends(self) -> None:
        """Analyze health trends for all components"""
        current_time = datetime.now()
        
        for component_key, history in self._health_history.items():
            try:
                if len(history) < 10:  # Need minimum data points
                    continue
                
                # Analyze trends for different time windows
                self._analyze_component_trend(component_key, history, 1)  # 1 hour
                self._analyze_component_trend(component_key, history, 6)  # 6 hours
                self._analyze_component_trend(component_key, history, 24)  # 24 hours
                
            except Exception as e:
                logger.error("Error analyzing trends for %s: %s", component_key, e)
    
    def _analyze_component_trend(self, component_key: str, history: deque, hours: int) -> None:
        """Analyze trend for a specific component and time window"""
        cutoff_time = datetime.now() - timedelta(hours=hours)
        recent_data = [h for h in history if h['timestamp'] >= cutoff_time]
        
        if len(recent_data) < 5:
            return
        
        # Analyze response time trend
        response_times = [h['response_time_ms'] for h in recent_data if h['response_time_ms'] is not None]
        if len(response_times) >= 5:
            trend = self._calculate_trend(response_times)
            
            trend_key = f"{component_key}:response_time:{hours}h"
            self._health_trends[trend_key] = HealthTrend(
                component=component_key,
                metric_name="response_time",
                trend_direction=trend['direction'],
                trend_strength=trend['strength'],
                data_points=len(response_times),
                time_window_hours=hours,
                prediction=trend.get('prediction')
            )
    
    def _calculate_trend(self, values: List[float]) -> Dict[str, Any]:
        """Calculate trend direction and strength for a series of values"""
        if len(values) < 3:
            return {"direction": "stable", "strength": 0.0}
        
        # Simple linear regression to determine trend
        x = list(range(len(values)))
        n = len(values)
        
        sum_x = sum(x)
        sum_y = sum(values)
        sum_xy = sum(x[i] * values[i] for i in range(n))
        sum_x2 = sum(x[i] ** 2 for i in range(n))
        
        # Calculate slope
        slope = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x ** 2)
        
        # Determine trend direction and strength
        if abs(slope) < 0.1:
            direction = "stable"
            strength = 0.0
        elif slope > 0:
            direction = "degrading"  # Increasing response time is degrading
            strength = min(1.0, abs(slope) / max(values))
        else:
            direction = "improving"  # Decreasing response time is improving
            strength = min(1.0, abs(slope) / max(values))
        
        return {
            "direction": direction,
            "strength": strength,
            "slope": slope
        }
    
    def _generate_periodic_reports(self) -> None:
        """Generate periodic health reports"""
        # Generate reports every hour
        current_time = datetime.now()
        if current_time.minute == 0:  # Top of the hour
            try:
                report = self.generate_health_report()
                self._store_health_report(report)
                logger.info("Generated periodic health report: %s", report.report_id)
            except Exception as e:
                logger.error("Error generating periodic health report: %s", e)
    
    def _store_health_report(self, report: SystemHealthReport) -> None:
        """Store health report for historical analysis"""
        # Implementation would depend on storage system
        # For now, just log the report summary
        logger.info("Health Report %s: Overall=%s, Active Alerts=%d, Components=%d",
                   report.report_id, report.overall_health.value,
                   len(report.active_alerts), len(report.component_health))
    
    def generate_health_report(self) -> SystemHealthReport:
        """Generate comprehensive system health report"""
        with self._lock:
            report_id = f"HR_{int(time.time())}"
            timestamp = datetime.now()
            
            # Determine overall health
            overall_health = self._calculate_overall_health()
            
            # Get component health snapshot
            component_health = dict(self._component_health)
            
            # Get active alerts
            active_alerts = [alert for alert in self._active_alerts.values() if not alert.resolved]
            
            # Get health trends
            health_trends = list(self._health_trends.values())
            
            # Get performance summary
            performance_summary = self.performance_monitor.get_current_performance_status()
            
            # Get security summary
            security_summary = self.metrics_collector.get_security_incident_metrics(24)
            
            # Generate recommendations
            recommendations = self._generate_health_recommendations(
                overall_health, active_alerts, health_trends
            )
            
            return SystemHealthReport(
                report_id=report_id,
                timestamp=timestamp,
                overall_health=overall_health,
                component_health=component_health,
                active_alerts=active_alerts,
                health_trends=health_trends,
                performance_summary=performance_summary,
                security_summary=security_summary,
                recommendations=recommendations,
                next_report_time=timestamp + timedelta(hours=1)
            )
    
    def _calculate_overall_health(self) -> HealthStatus:
        """Calculate overall system health status"""
        if not self._component_health:
            return HealthStatus.UNKNOWN
        
        # Count components by status
        status_counts = defaultdict(int)
        for component in self._component_health.values():
            status_counts[component.status] += 1
        
        total_components = len(self._component_health)
        
        # Determine overall health based on component statuses
        if status_counts[HealthStatus.CRITICAL] > 0:
            return HealthStatus.CRITICAL
        elif status_counts[HealthStatus.DEGRADED] > total_components * 0.3:  # More than 30% degraded
            return HealthStatus.DEGRADED
        elif status_counts[HealthStatus.WARNING] > total_components * 0.5:  # More than 50% warning
            return HealthStatus.WARNING
        elif status_counts[HealthStatus.HEALTHY] > total_components * 0.8:  # More than 80% healthy
            return HealthStatus.HEALTHY
        else:
            return HealthStatus.WARNING
    
    def _generate_health_recommendations(self, overall_health: HealthStatus,
                                       active_alerts: List[HealthAlert],
                                       trends: List[HealthTrend]) -> List[str]:
        """Generate health recommendations based on current status"""
        recommendations = []
        
        if overall_health == HealthStatus.CRITICAL:
            recommendations.append("IMMEDIATE ACTION REQUIRED: System is in critical state")
            recommendations.append("Review and resolve all critical alerts immediately")
        
        elif overall_health == HealthStatus.DEGRADED:
            recommendations.append("System performance is degraded - investigate root causes")
            recommendations.append("Consider scaling resources or optimizing performance")
        
        # Alert-based recommendations
        critical_alerts = [a for a in active_alerts if a.severity == AlertSeverity.CRITICAL]
        if critical_alerts:
            recommendations.append(f"Address {len(critical_alerts)} critical alerts immediately")
        
        # Trend-based recommendations
        degrading_trends = [t for t in trends if t.trend_direction == "degrading" and t.trend_strength > 0.5]
        if degrading_trends:
            recommendations.append(f"Monitor {len(degrading_trends)} components showing degrading trends")
        
        # Performance-based recommendations
        if any("queue_depth" in str(a.component) for a in active_alerts):
            recommendations.append("Consider increasing queue processing capacity")
        
        if any("cpu_usage" in str(a.component) for a in active_alerts):
            recommendations.append("Consider CPU optimization or horizontal scaling")
        
        if any("memory_usage" in str(a.component) for a in active_alerts):
            recommendations.append("Consider memory optimization or increasing available memory")
        
        return recommendations
    
    def _assess_threshold_impact(self, metric_name: str, current_value: float, severity: AlertSeverity) -> str:
        """Assess impact of threshold violation"""
        impact_map = {
            "cpu_usage": f"High CPU usage ({current_value:.1f}%) may slow email processing",
            "memory_usage": f"High memory usage ({current_value:.1f}%) may cause system instability",
            "processing_latency": f"High processing latency ({current_value:.0f}ms) affects user experience",
            "classification_accuracy": f"Low classification accuracy ({current_value:.1f}%) affects workflow quality",
            "queue_depth": f"High queue depth ({current_value:.0f}) may cause processing delays",
            "security_incidents": f"Multiple security incidents ({current_value:.0f}) require immediate attention"
        }
        
        base_impact = impact_map.get(metric_name, f"Metric {metric_name} violation detected")
        
        if severity == AlertSeverity.CRITICAL:
            return f"CRITICAL: {base_impact}"
        else:
            return base_impact
    
    def _assess_component_impact(self, component: ComponentHealth) -> str:
        """Assess impact of component failure"""
        impact_map = {
            ComponentType.EMAIL_CLIENT: "Email monitoring may be interrupted",
            ComponentType.DATABASE: "Data persistence and retrieval affected",
            ComponentType.REDIS_QUEUE: "Event publishing and queuing disrupted",
            ComponentType.CLASSIFICATION_ENGINE: "Email classification unavailable",
            ComponentType.SECURITY_VALIDATOR: "Security validation compromised",
            ComponentType.EVENT_PUBLISHER: "Event publishing to downstream systems affected"
        }
        
        base_impact = impact_map.get(component.component_type, "Component functionality affected")
        
        if component.status == HealthStatus.CRITICAL:
            return f"CRITICAL: {base_impact}"
        else:
            return base_impact
    
    def _get_threshold_recommendations(self, metric_name: str, severity: AlertSeverity) -> List[str]:
        """Get recommendations for threshold violations"""
        recommendations_map = {
            "cpu_usage": [
                "Optimize CPU-intensive operations",
                "Consider horizontal scaling",
                "Profile application for CPU hotspots"
            ],
            "memory_usage": [
                "Optimize memory usage patterns",
                "Increase available memory",
                "Implement memory pooling"
            ],
            "processing_latency": [
                "Optimize email processing pipeline",
                "Add performance monitoring",
                "Consider caching frequently accessed data"
            ],
            "classification_accuracy": [
                "Review and retrain classification models",
                "Increase manual review threshold",
                "Analyze classification errors"
            ],
            "queue_depth": [
                "Increase queue processing workers",
                "Optimize queue processing algorithms",
                "Implement queue partitioning"
            ],
            "security_incidents": [
                "Investigate security incidents immediately",
                "Review security policies",
                "Implement additional security controls"
            ]
        }
        
        recommendations = recommendations_map.get(metric_name, ["Investigate and resolve issue"])
        
        if severity == AlertSeverity.CRITICAL:
            recommendations.insert(0, "IMMEDIATE ACTION REQUIRED")
        
        return recommendations
    
    def _get_component_recommendations(self, component: ComponentHealth) -> List[str]:
        """Get recommendations for component issues"""
        recommendations_map = {
            ComponentType.EMAIL_CLIENT: [
                "Check email server connectivity",
                "Verify credentials and authentication",
                "Restart email client connection"
            ],
            ComponentType.DATABASE: [
                "Check database connectivity",
                "Verify database server status",
                "Review database logs for errors"
            ],
            ComponentType.REDIS_QUEUE: [
                "Check Redis server status",
                "Verify Redis connectivity",
                "Review Redis logs for errors"
            ],
            ComponentType.CLASSIFICATION_ENGINE: [
                "Check classification model availability",
                "Verify model dependencies",
                "Restart classification service"
            ]
        }
        
        recommendations = recommendations_map.get(component.component_type, ["Investigate component issue"])
        
        if component.status == HealthStatus.CRITICAL:
            recommendations.insert(0, "IMMEDIATE ATTENTION REQUIRED")
        
        return recommendations
    
    def acknowledge_alert(self, alert_id: str, acknowledged_by: str) -> bool:
        """Acknowledge an active alert"""
        with self._lock:
            if alert_id in self._active_alerts:
                alert = self._active_alerts[alert_id]
                alert.acknowledged = True
                alert.metadata["acknowledged_by"] = acknowledged_by
                alert.metadata["acknowledged_at"] = datetime.now().isoformat()
                
                logger.info("Alert acknowledged: %s by %s", alert_id, acknowledged_by)
                return True
            return False
    
    def resolve_alert(self, alert_id: str, resolved_by: str, resolution_notes: str = "") -> bool:
        """Resolve an active alert"""
        with self._lock:
            if alert_id in self._active_alerts:
                alert = self._active_alerts[alert_id]
                alert.resolved = True
                alert.resolution_time = datetime.now()
                alert.metadata["resolved_by"] = resolved_by
                alert.metadata["resolution_notes"] = resolution_notes
                
                # Remove from active alerts
                del self._active_alerts[alert_id]
                
                logger.info("Alert resolved: %s by %s", alert_id, resolved_by)
                return True
            return False
    
    def get_active_alerts(self, severity_filter: Optional[AlertSeverity] = None) -> List[HealthAlert]:
        """Get list of active alerts"""
        with self._lock:
            alerts = list(self._active_alerts.values())
            
            if severity_filter:
                alerts = [a for a in alerts if a.severity == severity_filter]
            
            return sorted(alerts, key=lambda x: x.timestamp, reverse=True)
    
    def get_component_health_status(self, component_type: Optional[ComponentType] = None) -> Dict[str, ComponentHealth]:
        """Get health status of components"""
        with self._lock:
            if component_type:
                return {k: v for k, v in self._component_health.items() 
                       if v.component_type == component_type}
            return dict(self._component_health)
    
    def get_health_trends(self, component: Optional[str] = None, hours: int = 24) -> List[HealthTrend]:
        """Get health trends for components"""
        with self._lock:
            trends = list(self._health_trends.values())
            
            if component:
                trends = [t for t in trends if component in t.component]
            
            # Filter by time window
            trends = [t for t in trends if t.time_window_hours <= hours]
            
            return sorted(trends, key=lambda x: x.trend_strength, reverse=True)
    
    def export_health_data(self, include_history: bool = False) -> Dict[str, Any]:
        """Export health data for external systems"""
        with self._lock:
            export_data = {
                "timestamp": datetime.now().isoformat(),
                "overall_health": self._calculate_overall_health().value,
                "component_health": {
                    k: {
                        "status": v.status.value,
                        "uptime_percentage": v.uptime_percentage,
                        "error_count": v.error_count,
                        "last_check": v.last_check.isoformat(),
                        "response_time_ms": v.response_time_ms
                    } for k, v in self._component_health.items()
                },
                "active_alerts": [
                    {
                        "id": a.alert_id,
                        "type": a.alert_type.value,
                        "severity": a.severity.value,
                        "component": a.component,
                        "description": a.description,
                        "timestamp": a.timestamp.isoformat()
                    } for a in self._active_alerts.values()
                ],
                "health_trends": [
                    {
                        "component": t.component,
                        "metric": t.metric_name,
                        "direction": t.trend_direction,
                        "strength": t.trend_strength
                    } for t in self._health_trends.values()
                ]
            }
            
            if include_history:
                export_data["alert_history_count"] = len(self._alert_history)
                export_data["health_history_components"] = len(self._health_history)
            
            return export_data