"""add_celery_and_email_queue_logging_tables

Revision ID: 5667efdb81b0
Revises: bbe85c9252e4
Create Date: 2025-08-30 15:49:35.763615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5667efdb81b0'
down_revision: Union[str, Sequence[str], None] = 'bbe85c9252e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('eo_id', sa.String(length=36), nullable=True),
    sa.Column('email_log_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_task_logs_email_log_id'), 'celery_task_logs', ['email_log_id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_eo_id'), 'celery_task_logs', ['eo_id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_status'), 'celery_task_logs', ['status'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_task_id'), 'celery_task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_task_name'), 'celery_task_logs', ['task_name'], unique=False)
    op.create_table('email_queue_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('to_addresses', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('email_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processor_worker', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_processing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_response_code', sa.Integer(), nullable=True),
    sa.Column('smtp_response_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_rate_limited', sa.Boolean(), nullable=False),
    sa.Column('outbox_saved', sa.Boolean(), nullable=False),
    sa.Column('outbox_path', sa.String(length=1024), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('email_log_id', sa.String(length=36), nullable=True),
    sa.Column('eo_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_queue_logs_celery_task_id'), 'email_queue_logs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_email_queue_logs_email_id'), 'email_queue_logs', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_queue_logs_email_log_id'), 'email_queue_logs', ['email_log_id'], unique=False)
    op.create_index(op.f('ix_email_queue_logs_email_type'), 'email_queue_logs', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_queue_logs_eo_id'), 'email_queue_logs', ['eo_id'], unique=False)
    op.create_index(op.f('ix_email_queue_logs_status'), 'email_queue_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_queue_logs_status'), table_name='email_queue_logs')
    op.drop_index(op.f('ix_email_queue_logs_eo_id'), table_name='email_queue_logs')
    op.drop_index(op.f('ix_email_queue_logs_email_type'), table_name='email_queue_logs')
    op.drop_index(op.f('ix_email_queue_logs_email_log_id'), table_name='email_queue_logs')
    op.drop_index(op.f('ix_email_queue_logs_email_id'), table_name='email_queue_logs')
    op.drop_index(op.f('ix_email_queue_logs_celery_task_id'), table_name='email_queue_logs')
    op.drop_table('email_queue_logs')
    op.drop_index(op.f('ix_celery_task_logs_task_name'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_task_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_status'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_eo_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_email_log_id'), table_name='celery_task_logs')
    op.drop_table('celery_task_logs')
    # ### end Alembic commands ###
