"""add_task_updates_and_daily_eo_summaries

Revision ID: 79ac9ac454be
Revises: fcc836971b2d
Create Date: 2025-08-29 15:55:56.245835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ac9ac454be'
down_revision: Union[str, Sequence[str], None] = 'fcc836971b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_eo_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eo_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress_summary', sa.Text(), nullable=True),
    sa.Column('key_blockers', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('attention_items', sa.JSON(), nullable=True),
    sa.Column('missing_updates', sa.JSON(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('updated_tasks', sa.Integer(), nullable=False),
    sa.Column('summary_email_sent', sa.Boolean(), nullable=False),
    sa.Column('summary_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eo_id'], ['executive_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_eo_summaries_date'), 'daily_eo_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_daily_eo_summaries_eo_id'), 'daily_eo_summaries', ['eo_id'], unique=False)
    op.create_table('task_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eo_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NotStarted', 'InProgress', 'Blocked', 'Completed', name='task_update_status', native_enum=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('blockers', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('spent_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_email_message_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eo_id'], ['executive_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_updates_date'), 'task_updates', ['date'], unique=False)
    op.create_index(op.f('ix_task_updates_dedupe_hash'), 'task_updates', ['dedupe_hash'], unique=False)
    op.create_index(op.f('ix_task_updates_eo_id'), 'task_updates', ['eo_id'], unique=False)
    op.create_index(op.f('ix_task_updates_source_email_message_id'), 'task_updates', ['source_email_message_id'], unique=False)
    op.create_index(op.f('ix_task_updates_task_id'), 'task_updates', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_updates_user_id'), 'task_updates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_updates_user_id'), table_name='task_updates')
    op.drop_index(op.f('ix_task_updates_task_id'), table_name='task_updates')
    op.drop_index(op.f('ix_task_updates_source_email_message_id'), table_name='task_updates')
    op.drop_index(op.f('ix_task_updates_eo_id'), table_name='task_updates')
    op.drop_index(op.f('ix_task_updates_dedupe_hash'), table_name='task_updates')
    op.drop_index(op.f('ix_task_updates_date'), table_name='task_updates')
    op.drop_table('task_updates')
    op.drop_index(op.f('ix_daily_eo_summaries_eo_id'), table_name='daily_eo_summaries')
    op.drop_index(op.f('ix_daily_eo_summaries_date'), table_name='daily_eo_summaries')
    op.drop_table('daily_eo_summaries')
    # ### end Alembic commands ###
