"""add_ai_summary_to_task_updates

Revision ID: bbe85c9252e4
Revises: 79ac9ac454be
Create Date: 2025-08-29 17:44:27.694937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe85c9252e4'
down_revision: Union[str, Sequence[str], None] = '79ac9ac454be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_updates', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_updates', 'ai_summary')
    # ### end Alembic commands ###
