"""add_password_hash_to_users

Revision ID: e03595c77529
Revises: 1b7a3157e0a7
Create Date: 2025-08-25 15:20:04.505422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03595c77529'
down_revision: Union[str, Sequence[str], None] = '1b7a3157e0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_executive_orders_message_id'), 'executive_orders', type_='unique')
    op.create_index(op.f('ix_executive_orders_message_id'), 'executive_orders', ['message_id'], unique=True)
    op.drop_constraint(op.f('uq_tasks_eo_id_title'), 'tasks', type_='unique')
    
    # Add password_hash column as nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    
    # Update existing users with a default password hash
    # This is a temporary hash that will be updated by the script
    import bcrypt
    default_hash = bcrypt.hashpw("Lumen@2025".encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    op.execute(f"UPDATE users SET password_hash = '{default_hash}' WHERE password_hash IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.create_unique_constraint(op.f('uq_tasks_eo_id_title'), 'tasks', ['eo_id', 'title'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_executive_orders_message_id'), table_name='executive_orders')
    op.create_unique_constraint(op.f('uq_executive_orders_message_id'), 'executive_orders', ['message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
