"""add_eo_pmo_assignments_table

Revision ID: fcc836971b2d
Revises: 62d804a27b5a
Create Date: 2025-08-26 15:19:44.092190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc836971b2d'
down_revision: Union[str, Sequence[str], None] = '62d804a27b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_pmo_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eo_id', sa.Uuid(), nullable=False),
    sa.Column('pmo_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eo_id'], ['executive_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pmo_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eo_id', 'pmo_id', name='uq_eo_pmo_assignment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_pmo_assignments')
    # ### end Alembic commands ###
